reportjira:
  image: 'albertalvarezbruned/reportjira'
  container_name: 'reportjira'
  volumes:
    - '/tmp/.X11-unix:/tmp/.X11-unix'
    - '/path/to/file.yaml:/root/file.yaml'
    - '/path/to/images/:/root/images/'
  environment:
    - 'DISPLAY=:0'
